# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [repository_dispatch]
  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  update-uasier:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Working'
        env:
          SCKEY: ${{ secrets.YUQUESECRET }}
        run: python uasier/main.py